# 0.1 Data Adquisition

## Fuente del dataset
TEXTO

## Fundamentos de la eleccion

De todos los encontrados realizamos una segunda selecci칩n teniendo en cuenta diferentes parametros como:
- Tema a tratar:Debe ser interesante para los3integrantes del grupo.
- Objetivo y resultados:El Dataset debe permitir realizar un an치lisis completo.
- Datos suficientes:El dataset debe contener muchos atributos y registros para facilitar el aprendizaje de nuestros algoritmos de Machine Learning.
- Originalidad:El tema a tratar debe ser original en la comisi칩n.
- Calidad:El trabajo finalizado debe ser de calidad.Para poder formar parte de nuestro Portfolio.
Nos decidimos a trabajar sobre el tema viviendas. Un dataset que cuenta con 2930 registros y 80 atributos. Los atributos correspondenadiferentes caracteristicas de cada vivienda.
   https://www.kaggle.com/prevek10/ames-housing-dataset

## Import libraries

In [27]:
# Sirve para actualizar el modulo despues de haber cambiado algo en el codigo de los modulos importados
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# Modulo para trabajar con los directorios del proyecto
from src.utils.paths import data_dir

## Set up

In [35]:
# Configuramos para que muestre siempre todas las columnas disponibles
pd.options.display.max_columns = None
# Cambio del tama침o de los plots para seaborn
sns.set(rc={'figure.figsize':(10,5)})

## Read Data

In [30]:
# Obtenemos la ruta de los csv's que vamos a utilizar
WINE_RAW_CSV_PATH = data_dir("raw", "wine_dataset.csv")
WINES_SPA_RAW_CSV_PATH = data_dir("raw", "wines_SPA.csv")

WINE_RAW_CSV_PATH , WINES_SPA_RAW_CSV_PATH

(WindowsPath('c:/Users/cvigo/data-projects/vinos_coderhouse/data/raw/wine_dataset.csv'),
 WindowsPath('c:/Users/cvigo/data-projects/vinos_coderhouse/data/raw/wines_SPA.csv'))

In [31]:
# Leemos los csv's y los guardamos en un dataframe
df_wine = pd.read_csv(WINE_RAW_CSV_PATH)
df_wine_spa = pd.read_csv(WINES_SPA_RAW_CSV_PATH)

In [32]:
# Mostramos el shape de ambos datasets
print(f"{df_wine.shape =}")
print(f"{df_wine_spa.shape =}")

df_wine.shape =(6497, 13)
df_wine_spa.shape =(7500, 11)

Como tenemos dos datasets vamos a trabajarlos por separado en primera instancia para ver como los podemos unificar luego y hacer un analisis integrado

## Wine Dataset

In [33]:
# Vista previa de 10 datos aleatorios
df_wine.sample(10)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
490,9.3,0.775,0.27,2.80,0.078,24.0,56.0,0.99840,3.31,0.67,10.6,6,red
5623,6.0,0.280,0.27,4.10,0.046,50.0,147.0,0.99126,3.27,0.56,11.6,6,white
5760,7.4,0.160,0.30,13.70,0.056,33.0,168.0,0.99825,2.90,0.44,8.7,7,white
2458,6.6,0.300,0.30,4.80,0.170,60.0,166.0,0.99460,3.18,0.47,9.4,5,white
4159,6.9,0.320,0.26,2.30,0.030,11.0,103.0,0.99106,3.06,0.42,11.1,6,white
1689,7.2,0.390,0.63,11.00,0.044,55.0,156.0,0.99740,3.09,0.44,8.7,6,white
5158,7.5,0.340,0.24,3.85,0.031,5.0,34.0,0.99098,3.01,0.36,11.8,4,white
4326,6.5,0.170,0.31,1.50,0.041,34.0,121.0,0.99092,3.06,0.46,10.5,6,white
5527,6.6,0.320,0.47,15.60,0.063,27.0,173.0,0.99872,3.18,0.56,9.0,5,white
290,8.7,0.520,0.09,2.50,0.091,20.0,49.0,0.99760,3.34,0.86,10.6,7,red

### Data Dictionary - Wine Dataset

- fixed_acidity: 
- volatile_acidity: 
- citric_acid: 
- residual_sugar: 
- chlorides: 
- free_sulfur_dioxide: 
- total_sulfur_dioxide: 
- density: 
- pH: 
- sulphates: 
- alcohol: 
- quality: 
- style:

## Wine SPA Dataset

In [34]:
# Vista previa de 10 datos aleatorios
df_wine_spa.sample(10)

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
6815,Binigrau,Nounat,2020,4.2,404,Espana,Mallorca,19.90,NaN,NaN,NaN
7158,La Rioja Alta,Vina Alberdi Crianza,2018,4.2,410,Espana,Rioja,13.58,Rioja Red,NaN,NaN
370,Aalto,PS (Pagos Seleccionados) Ribera del Duero,2011,4.5,2207,Espana,Ribera del Duero,64.00,Ribera Del Duero Red,5.0,3.0
5071,Mustiguillo,Finca Terrerazo,2017,4.2,390,Espana,El Terrerazo,24.45,Red,4.0,3.0
2687,Lustau,Candela Cream Dulce Sweet,N.V.,4.2,405,Espana,Jerez-Xeres-Sherry,7.10,Sherry,4.0,3.0
3526,Enrique Mendoza,Santa Rosa,2017,4.2,420,Espana,Alicante,18.90,Red,4.0,3.0
25,Vega Sicilia,Unico,1979,4.8,118,Espana,Ribera del Duero,815.00,Ribera Del Duero Red,5.0,3.0
7129,Sierra Cantabria,Coleccion Privada,2012,4.2,420,Espana,Rioja,28.30,Rioja Red,4.0,3.0
1022,Vinas del Vero,Blecua Somontano,2014,4.4,43,Espana,Somontano,74.95,Red,4.0,3.0
1640,La Rioja Alta,Rioja Gran Reserva 904,1970,4.3,53,Espana,Rioja,260.00,Rioja Red,4.0,3.0

### Data Dictionary - Wine SPA Dataset

- winery: 
- wine: 
- year: 
- rating: 
- num_reviews: 
- country: 
- region: 
- price: 
- type: 
- body: 
- acidity: